version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  # rabbit-mq:
  #   image: rabbitmq:3.12.7
  #   container_name: rabbitmq
  #   ports:
  #     - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
  #   env_file:
  #     - .env
