export enum OrderStatusTypes {
  CREATED = 'CREATED',
  CANCELLED = 'CANCELLED',
  ASSIGNED = 'ASSIGNED',
  DELIVERED = 'DELIVERED',
  PAID = 'PAID',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
  REPORTED = 'REPORTED',
}
